### ISSUE TITLE
All content URLs should use same root as RSS feeds

### ISSUE THREAD

**Issue by ericcylogy** [fargeo/baaqmd-maps#20]
Currently, content links (such as http://www.baaqmd.gov/Utils/Interactive-Map-Content/About-Forecast) are hardcoded to www.baaqmd.gov. These should use the same root as the RSS feeds. Replacing the root is sufficient, the paths are always identical between environments. Ultimately there should be no instances of "www.baaqmd.gov" in the code.

**Comment by victorpivniuk** [comment]
[NOT REQUIRED, just nice to have]
Also, all RSS feeds URLs better not contain ".aspx" extension. So, URL should be like http://www.baaqmd.gov/Feeds/OpenBurnRSS

**Comment by robgaston** [comment]
@ericcylogy @victorpivniuk this should be fixed in the latest; can you please confirm when you get a chance? thanks!

**Comment by victorpivniuk** [comment]
@robgaston works fine, thanks!

**Comment by robgaston** [comment]
@victorpivniuk Thanks!
