### ISSUE TITLE
Accommodate more than two environments in options

### ISSUE THREAD

**Issue by ericcylogy** [fargeo/baaqmd-maps#21]
Currently, the switch to using a Dev root is a boolean, so the roots are dev or production. We will ultimately need additional environments accommodated. This could probably be handled just by allowing the root to be set as an option, unless the current code uses the dev switch for something other than switching out the root.

**Comment by robgaston** [comment]
@ericcylogy this should be fixed in the latest; can you please confirm when you get a chance? thanks!

**Comment by victorpivniuk** [comment]
Hi @robgaston . Can you pls expose map token as param too?

**Comment by robgaston** [comment]
@victorpivniuk I added this in the following commit on Monday: https://github.com/fargeo/baaqmd-maps/commit/2120f660bcae07aaaa62736c95432746f7f63dc9

You can now use the parameter `accessToken` for this, as described in [README.md](https://github.com/fargeo/baaqmd-maps/blob/master/README.md)

**Comment by victorpivniuk** [comment]
@robgaston rootURL works fine, thank you. I'm just curios about accessToken. Looks like it is properly set to mapbox_gl object but there is variable `let mapboxQuery = '?access_token=' + config["accessToken"];` where default token is used always. I also see a lot of requests in chrome tools like `https://api.mapbox.com/styles/v1/baaqmd-publicmaps/cjv77q5gn2af61fkdmy2afi3w?access_token=pk.eyJ1IjoiYmFhcW1kLXB1YmxpY21hcHMiLCJhIjoiY2szcDJsMTRlMjdnYTNicGhrNGZncXhuYyJ9.iV06_RIzAx1lImQdB-uiMw` where default token is in query.

**Comment by robgaston** [comment]
@victorpivniuk great catch! We manually fetch style objects from mapbox, which is where we were still using the default token (also, we used that token for geocoder requests). I just merged in a fix for that - thanks!

**Comment by victorpivniuk** [comment]
@robgaston it is good now, thanks! the case can be closed
