### ISSUE TITLE
Change AQI data url

### ISSUE THREAD

**Issue by victorpivniuk** [fargeo/baaqmd-maps#23]
Hey @robgaston 
URL /Files/Feeds/aqi_rss.xml is no longer available and was substituted by /Feeds/Air-Forecast-Map (i.e. https://www.baaqmd.gov/Feeds/Air-Forecast-Map )
Can you pls make the change in map?

**Comment by robgaston** [comment]
@victorpivniuk I just pushed a fix for this - thanks for alerting us!
